feat: add MongoDB container for local development
nyrkio/nyrkio pull request #252
Opened 2024-10-22 15:05 UTC by wagnerjfr

Updated README.md to provide the MongoDB DB_URL for local setup.
Modified docker-compose.dev.yml to configure MongoDB service for local development.

2024-10-22 19:56 UTC, mfleming requested changes
Overall looks good. Just a couple of minor changes requested.

Thanks for your contribution!

2024-10-22 19:56 UTC, mfleming commented on README.md
>  #DB_URL=mongodb://localhost:27017/nyrkiodb
I think we should just make running mongo in a container the default and remove all other `DB_URL` examples.

2024-10-22 19:56 UTC, mfleming commented on docker-compose.dev.yml
> +    restart: always
Unintentional change? Looks like you removed the newline at the end of the file.

2024-10-22 20:12 UTC, wagnerjfr reviewed
Addressed the suggestions

2024-10-24 19:29 UTC, wagnerjfr commented
Let me know if the change is ok

2024-10-25 09:43 UTC, mfleming approved these changes
lgtm thanks!

2024-10-25 09:50 UTC, merged